### PR TITLE
Update CORE_SYMBOL_NAME to "EOS" by default in build bootstrap script

### PR DESCRIPTION
**Pull request by robrigo**
Update the CORE_SYMBOL_NAME to EOS in preparation for the mainnet.

### CODE REVIEW

**Comment by sebicas** [comment]
@nsjames can you please merge this?

**Comment by kesar** [comment]
Can't we just use ./eosio_build.sh -s EOS ? I would rather create a new file eosio_mainnet.sh (or similar) that just call the other one with that param.

My concern is that we may end up with conflicts, and a new file especific for our needs wont have conflicts and can grow with more improvements related to our mainnet. 👍

**Comment by sebicas** [comment]
@kesar you will see a lot of people building with out the "-s EOS"

> My concern is that we may end up with conflicts

Like what type of conflicts?

**Comment by kesar** [comment]
like any refactoring in CMakelist, a file that changes very often.

Whats the problem with use a parameter in eos_build.sh?

**Comment by kaidiren** [comment]
this rep is just for mainnet, useing parameter is  very easy to missing

**Comment by sebicas** [comment]
> using parameter is very easy to missing

1. This! I most people will miss that parameter
2. This repo should build EOS Main-net by default

**Comment by gustavomick** [comment]
any update?

**Comment by kesar** [comment]
> any update?

Yes, we need more consensus to get this merged. We should try to get people from other BPs involved. 👍 

First of all, change code in this repo without setting a build system its a negligence in my opinion. Block1 has proper build system for their repository, if we start to change code without applying tests, we are potentially breaking the system.

This already occurred yesterday.

> I think most people will miss this parameter

If a BP miss this important parameter, means that the BP is not taking enough care about this project, and in the worst case, he wont be able to produce blocks if that producer get eventually voted in.

> We like to make it easy for developers to build a local EOS node from this repo.

Developers dont need to compile even with the EOS symbol.

The worst case scenario of changing this code, will be that ALL the BPs get updated with a wrong code, and that could be pretty bad compared with the BP missing the parameter when he is building.

**Comment by bitcoiners** [comment]
I vote for merging.

**Comment by gustavomick** [comment]
may be instead of changing default could be forcing parameter to be required.

**Comment by bitcoiners** [comment]
Will this issue be resolved any time soon? What is the hold up?

**Comment by jrosich** [comment]
Using the parameter is very easy to remember. Cant see the issue here.

**Comment by bitcoiners** [comment]
Yes, not sure why it is taking 2 weeks to resolve.

**Comment by kesar** [comment]
> Yes, not sure why it is taking 2 weeks to resolve.

Basically because any addition to the eos change can break the whole system, and it seems very irresponsible IMHO. There is no governance, not even build system for this repository. In addition I can only see 1 elected BP that has voted to merge this.

For the sake of support accounting, in the name of what BP are you voting?

**Comment by bitcoiners** [comment]
I am not a BP or a representative of one. Just a member of the community.
However I think the fact that such a small issue being unresolved for weeks is a problem of organization, as you pointed, lack of governance for this repository, which should be addressed.

**Comment by robrigo** [comment]
This is obviously not going to get merged, so much discussion over a 3 letter change haha. I agree we need better governance and processes around this repo. Closing it.

**Pull request closed without merging**
