### PR TITLE
finish the delegated_bandwidth->self_delegated_bandwidth

### PR DESCRIPTION
**Pull request by EOSBIXIN**

### CODE REVIEW

**Comment by EOSBIXIN** [comment]
to fix the bug to get delegated account info:
```
cleos get account voter1111111
2735496ms thread-0   main.cpp:2659                 main                 ] Failed with error: Assert Exception (10)
itr != structs.end(): Unknown struct self_delegated_bandwidth
```

**Comment by jrosich** [comment]
Hi, I updated Jungle and still having the same error. Do we need to update all nodes to get it fixed? or its me? I checked all my scripts and they are pointing to the right binary

```
nodeos --version
759439493
./cleos.sh get account eosbarcelona
217686ms thread-0   main.cpp:2659                 main                 ] Failed with error: Assert Exception (10)
itr != structs.end(): Unknown struct self_delegated_bandwidth
```

**Comment by EOSBIXIN** [comment]
yes, it seems we can NOT upgrade the eosio.system. When I call:
 'cleos set contract eosio /opt/eosio/bin/data-dir/contracts/eosio.system -p eosio'
get ERROR:
```
cleos set contract eosio /opt/eosio/bin/data-dir/contracts/eosio.
Reading WAST/WASM from /opt/eosio/bin/data-dir/contracts/eosio.system/eosio.system.wasm...
Using already assembled WASM...
Publishing contract...
3026732ms thread-0   main.cpp:2659                 main                 ] Failed with error: Assert Exception (10)
account.code_version != code_id: contract is already running this version of code
```

so, you had better rm block and restart the chain

**Comment by jrosich** [comment]
thanks man. Great work!

**Comment by EOSBIXIN** [comment]
there is more suitable fix, please ignore this change, and you can check:
https://github.com/EOSIO/eos/commit/843ed6452f6bfc7deb74b660dfcd7758ba6a1775

**Pull request merged**
